### ISSUE TITLE
A08 Admin: Treasury - Deposit History

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#15]
Related to https://github.com/bitcoin-sv/bsv-faucet/issues/17 and https://github.com/bitcoin-sv/bsv-faucet/issues/14 and 

Description:
For admins (role = 2) there will be a dedicated section /admin to allow them to see and manage the overall treasury.

At the bottom of the page, show the "Treasury - Deposit History" section highlighting the latest transactions in the master wallet. 

Sorted by most recent. 

- Date
- Txid
- Beef TX
- vout
- tx type (deposit)
- Amount

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To implement this feature, I would create a dedicated `/admin` section accessible only to admins (role = 2), allowing them to view and manage the treasury. At the bottom of the page, I’ll add a "Treasury - Deposit History" section that displays the most recent transactions in the master wallet.

The transactions will be sorted by date, from most recent to oldest, and will include the following columns: Date, Txid, Raw TX, vout, tx type (which will always be ‘deposit’), and the Amount. This setup will provide admins with a clear and detailed view of deposit activity in the treasury, making it easier to track and manage transactions.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a frontend engineer with over 5 years experience.

### How I plan on tackling this issue
To tackle this issue:
I will create a table using tanstack  to display the latest transaction on the master wallet.
ETA: 24hrs

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I'm the maintainer of op-scan (https://github.com/walnuthq/op-scan) a blockchain explorer with a very similar tech stack so I'm familiar with the patterns and best practices used in this project. I will use my XP in Full Stack Web3 Development to implement this issue.

### How I plan on tackling this issue
The user story being self explanatory, I will carefully implement it using the latest Next.js best practices, choosing the right shadcn/ui component for the job, which is probably a simple Table or a more complex Data Table if we need ordering/sorting.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Here's my approach to implementing the Treasury Deposit History feature:

1. Data Structure & Fetching:
   - I'll implement pagination for transaction history
   - Set up WebSocket connection for real-time updates
   - Create efficient data caching strategy:


2. UI Implementation:
   - Build a responsive data table with sortable columns
   - Add transaction detail expansion panels
   - Include copy-to-clipboard for txids
   - Implement infinite scroll for better performance
   - Add proper loading states and error handling
   - Format dates to user's timezone

3. Transaction Details:
   - Create modal/drawer for detailed tx view
   - Add blockchain explorer links
   - Implement raw transaction data viewer
   - Add BSV/Satoshi toggle for amounts
   - Include confirmation status indicators

4. Filtering & Search:
   - Add date range filters
   - Implement amount range filtering
   - Add txid search functionality
   - Add export to CSV feature

Testing Strategy:
- Unit tests for data formatting
- Integration tests with blockchain API
- Performance testing with large datasets
- Cross-browser compatibility
- Mobile responsiveness

Expected Timeline: 3-4 days

Key Features:
- Real-time updates
- Efficient pagination
- Advanced filtering
- Detailed transaction view
- Data export capabilities

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I have extensive experience in full-stack web development, particularly in creating dashboards and administrative interfaces that allow users to manage complex data sets. My background in blockchain technology equips me with the skills to handle cryptocurrency transactions and their associated metadata securely. This experience enables me to implement the Treasury - Deposit History feature effectively, ensuring that admins can easily view and manage the latest transactions in the master wallet.



### How I plan on tackling this issue
To implement the "Treasury - Deposit History" section for the admin interface, I will ensure that all relevant deposit transaction data is recorded in the database. I will develop an API endpoint to fetch the deposit history, which will query the database for the most recent deposit transactions, sorted by date in descending order. 

In the `/admin` section, I will create a user-friendly table displaying the deposit history with columns for Date, Txid, Raw TX, Vout, Transaction Type, and Amount. The table will be populated with data retrieved from the API, ensuring it accurately reflects the latest deposit transactions. 

I will implement pagination or lazy loading if necessary to enhance performance. Additionally, I will write unit and integration tests to verify that the deposit history is fetched correctly and displayed accurately. Error handling will be incorporated to provide notifications in case of issues during data fetching. 

This approach will create a robust and intuitive feature that allows admins to effectively monitor and manage the overall treasury.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by blessingbytes** [comment]
Can I handle this task?
